services:  
  app:
    build: .
    container_name: documenso-app
    env_file:
      - ./config/.env.documenso
    ports:
      - "3000:3000"
    depends_on:
      - db
      - inbucket
    networks:
      - documenso_network
    volumes:
      - ./data:/app
      - ./config:/config
      - ./scripts:/init

  inbucket:
    image: inbucket/inbucket
    container_name: mailserver
    ports:
      - "19000:9000"
      - "2500:2500"
      - "1100:1100"
    networks:
      - documenso_network
    volumes:
      - ./inbucket-data:/data

  db:
    image: postgres:latest
    container_name: documenso-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: documenso
    ports:
      - "5432:5432"
    networks:
      - documenso_network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  documenso_network:
    driver: bridge
