services:
  web:
    build: .
    container_name: documenso-web
    command: bash -c "cd /app/documenso ; npm run prisma:migrate-deploy ; cd apps/remix ; npm run start ;"
    ports:
      - "8045:3000"
    depends_on:
      - db
      - mailhog
    networks:
      - documenso_network

  db:
    image: postgres:latest
    container_name: documenso-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=documenso
    networks:
      - documenso_network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      - documenso_network

networks:
  documenso_network:
    driver: bridge
